### ISSUE TITLE
Libssh2 Linux build failed

### ISSUE THREAD

**Issue by ruslo** [hunter-packages/libssh2#2]
@alamaison I've push latest version to testing and see some failed stuff: https://travis-ci.org/ingenue/hunter/builds/145236987 I don't know what changed (it was working before), probably this is because of FindOpenSSL update (?). I think we need to link CMAKE_DL_LIBS to OpenSSL::crypto. But first we need to use imported OpenSSL targets in Libssh2 instead of OPENSSL_LIBRARIES as far as I understand: https://github.com/hunter-packages/libssh2/blob/266056ce760d23998e60a4bb6064362257973215/src/CMakeLists.txt#L70

Needed for CURL: https://github.com/ruslo/hunter/pull/456

**Comment by alamaison** [comment]
Problem is in FindOpenSSL.  As you say, it needs `CMAKE_DL_LIBS`.  But libssh2 shouldn't need any changes to make this work.  Hunter should allow projects to function unmodified

**Comment by ruslo** [comment]
> But libssh2 shouldn't need any changes to make this work

It does use OPENSSL_LIBRARIES instead of `OpenSSL::SSL`/`OpenSSL::Crypto` so installed config file contains full paths. It's not relocatable. I guess you can make it cacheable by using imported targets.

**Comment by alamaison** [comment]
Right.  That's important, but unrelated.  I'll fix it separately.

**Comment by alamaison** [comment]
Done here: https://github.com/ruslo/hunter/pull/491
